apiVersion: v1
kind: Secret
metadata:
  name: secret-mq-auth
type: kubernetes.io/basic-auth
stringData:
  username: mq-user
  password: mq-password
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mongo-auth
type: kubernetes.io/basic-auth
stringData:
  username: mongo-user
  password: mongo-password
