apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  replicas: 4
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: indexer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: indexer
        tier: service
    spec:
      containers:
      - name: indexer
        image: "ghcr.io/simonh10/textindexer:mock"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 4010
        readinessProbe:
          httpGet:
            path: /indexer/v1/document
            port: 4010
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /indexer/v1/document
            port: 4010
          initialDelaySeconds: 5
          timeoutSeconds: 5       
        env:
        - name: PORT
          value: "4010"
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: indexer
    tier: service
spec:
  type: LoadBalancer
  ports:
  - port: 4010
  selector:
    app: indexer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /indexer/v1/
        pathType: Prefix
        backend:
          service:
            name: indexer
            port:
              number: 4010
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: "mongo-data-dir"
          persistentVolumeClaim: 
            claimName: "task-pv-claim"
      containers:
      - name: mongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/db"
