apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  replicas: 4
  revisionHistoryLimit: 10
  minReadySeconds: 5
  selector:
    matchLabels:
      app: indexer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: indexer
        tier: service
    spec:
      containers:
      - name: indexer
        image: "ghcr.io/simonh10/textindexer:main"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: indexer
    tier: service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: indexer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
  - http:
      paths:
      - path: /indexer/v1/
        pathType: Prefix
        backend:
          service:
            name: indexer
            port:
              number: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
        - name: "mongo-pv"
          persistentVolumeClaim: 
            claimName: "mongo-pvc"
      containers:
      - name: mongo
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: "mongo-pv"
            mountPath: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq
spec:
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      volumes:
        - name: "mq-data"
          persistentVolumeClaim: 
            claimName: "mq-pvc"
      containers:
      - name: mq
        image: rabbitmq
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: "mq-data"
            mountPath: "/var/lib/rabbitmq/mnesia"
