# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from textindexer.server.models.base_model_ import Model
from textindexer.server import util


class DocumentIndexTokens(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None, start=None):  # noqa: E501
        """DocumentIndexTokens - a model defined in OpenAPI

        :param token: The token of this DocumentIndexTokens.  # noqa: E501
        :type token: str
        :param start: The start of this DocumentIndexTokens.  # noqa: E501
        :type start: int
        """
        self.openapi_types = {
            'token': str,
            'start': int
        }

        self.attribute_map = {
            'token': 'token',
            'start': 'start'
        }

        self._token = token
        self._start = start

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentIndexTokens':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentIndex_tokens of this DocumentIndexTokens.  # noqa: E501
        :rtype: DocumentIndexTokens
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self):
        """Gets the token of this DocumentIndexTokens.


        :return: The token of this DocumentIndexTokens.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this DocumentIndexTokens.


        :param token: The token of this DocumentIndexTokens.
        :type token: str
        """

        self._token = token

    @property
    def start(self):
        """Gets the start of this DocumentIndexTokens.


        :return: The start of this DocumentIndexTokens.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this DocumentIndexTokens.


        :param start: The start of this DocumentIndexTokens.
        :type start: int
        """

        self._start = start
