# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from textindexer.server.models.base_model_ import Model
from textindexer.server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, docs=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param docs: The docs of this InlineResponse200.  # noqa: E501
        :type docs: List[str]
        """
        self.openapi_types = {
            'docs': List[str]
        }

        self.attribute_map = {
            'docs': 'docs'
        }

        self._docs = docs

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def docs(self):
        """Gets the docs of this InlineResponse200.


        :return: The docs of this InlineResponse200.
        :rtype: List[str]
        """
        return self._docs

    @docs.setter
    def docs(self, docs):
        """Sets the docs of this InlineResponse200.


        :param docs: The docs of this InlineResponse200.
        :type docs: List[str]
        """

        self._docs = docs
