# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from textindexer.server.models.base_model_ import Model
from textindexer.server import util


class WordReferences(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, index=None, paragraph=None, start=None):  # noqa: E501
        """WordReferences - a model defined in OpenAPI

        :param index: The index of this WordReferences.  # noqa: E501
        :type index: str
        :param paragraph: The paragraph of this WordReferences.  # noqa: E501
        :type paragraph: int
        :param start: The start of this WordReferences.  # noqa: E501
        :type start: int
        """
        self.openapi_types = {
            'index': str,
            'paragraph': int,
            'start': int
        }

        self.attribute_map = {
            'index': 'index',
            'paragraph': 'paragraph',
            'start': 'start'
        }

        self._index = index
        self._paragraph = paragraph
        self._start = start

    @classmethod
    def from_dict(cls, dikt) -> 'WordReferences':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Word_references of this WordReferences.  # noqa: E501
        :rtype: WordReferences
        """
        return util.deserialize_model(dikt, cls)

    @property
    def index(self):
        """Gets the index of this WordReferences.


        :return: The index of this WordReferences.
        :rtype: str
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this WordReferences.


        :param index: The index of this WordReferences.
        :type index: str
        """

        self._index = index

    @property
    def paragraph(self):
        """Gets the paragraph of this WordReferences.


        :return: The paragraph of this WordReferences.
        :rtype: int
        """
        return self._paragraph

    @paragraph.setter
    def paragraph(self, paragraph):
        """Sets the paragraph of this WordReferences.


        :param paragraph: The paragraph of this WordReferences.
        :type paragraph: int
        """

        self._paragraph = paragraph

    @property
    def start(self):
        """Gets the start of this WordReferences.


        :return: The start of this WordReferences.
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this WordReferences.


        :param start: The start of this WordReferences.
        :type start: int
        """

        self._start = start
