# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from textindexer.server.models.base_model_ import Model
from textindexer.server.models.word import Word
from textindexer.server import util

from textindexer.server.models.word import Word  # noqa: E501

class Words(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, count=None, words=None):  # noqa: E501
        """Words - a model defined in OpenAPI

        :param count: The count of this Words.  # noqa: E501
        :type count: int
        :param words: The words of this Words.  # noqa: E501
        :type words: Word
        """
        self.openapi_types = {
            'count': int,
            'words': Word
        }

        self.attribute_map = {
            'count': 'count',
            'words': 'words'
        }

        self._count = count
        self._words = words

    @classmethod
    def from_dict(cls, dikt) -> 'Words':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Words of this Words.  # noqa: E501
        :rtype: Words
        """
        return util.deserialize_model(dikt, cls)

    @property
    def count(self):
        """Gets the count of this Words.


        :return: The count of this Words.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this Words.


        :param count: The count of this Words.
        :type count: int
        """

        self._count = count

    @property
    def words(self):
        """Gets the words of this Words.


        :return: The words of this Words.
        :rtype: Word
        """
        return self._words

    @words.setter
    def words(self, words):
        """Sets the words of this Words.


        :param words: The words of this Words.
        :type words: Word
        """

        self._words = words
